---
# ToDo: this should be moved to a dedicated nginx vhost role

# Copy nginx block (vhost) config files
- name: Copy nginx block (vhost) config file to available sites
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/sites-available/{{ rocket_chat_fqdn }}.conf"
  with_items:
    - vhost.conf
  notify: "reload nginx"
  become: yes

- name: Enable nginx block config
  file:
    src: "/etc/nginx/sites-available/{{ rocket_chat_fqdn }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ rocket_chat_fqdn }}.conf"
    state: link
  notify: "reload nginx"
  become: yes
